# -*- coding: utf-8 -*-
"""Add_strings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H5v6l5duGArO-FTRFkZ5rNOEiMcOWI0C
"""

class Solution:
    def firstUniqChar(self, s: str) -> int:
        if len(s)==0:
            return -1
        for i in range(len(s)):
            if s.count(s[i])<2:
                return i
        return -1