# -*- coding: utf-8 -*-
"""Buddy_String.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e7Mfzb1uh_EkZSkeN5fIrr4YfMr2GMqW
"""

class Solution:
    def buddyStrings(self, A: str, B: str) -> bool:
        if len(A)!=len(B):
            return False
        if A==B and len(set(A))<len(A):
            return True
        d=[]
        for i in range(len(A)):
            if A[i]!=B[i]:
                d.append((A[i],B[i]))
        print(d)
        return len(d)==2 and d[0]==d[1][::-1]