# -*- coding: utf-8 -*-
"""Consecutive_characters

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e7Mfzb1uh_EkZSkeN5fIrr4YfMr2GMqW
"""

class Solution:
    def maxPower(self, s: str) -> int:
        max_till_now=1
        c=1
        for i in range(1,len(s)):
            if s[i]==s[i-1]:
                c += 1
            else:
                c = 1
            max_till_now = max(max_till_now,c)
        return max_till_now