# -*- coding: utf-8 -*-
"""Count and Say

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o-v6yd-ALmBK9e5tnB-WcuoAMyvDDoMO
"""

class Solution:
    def countAndSay(self, n: int) -> str:
        if n == 1:
            return "1"
        prev = self.countAndSay(n-1)
        r = ""
        c = 1
        for i in range(len(prev)):
            if i == len(prev)-1 or prev[i] != prev[i+1]:
                r = r + str(c) + prev[i]
                c = 1
            else:
                c = c + 1
        return r

