# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18WTAPGxLmzWF316S6D2QvDjeP2UmA3bd
"""

class Solution:
    def lengthOfLastWord(self, s: str) -> int:
        p = s.strip().split()
        return len(p[-1]) if p else 0

