# -*- coding: utf-8 -*-
"""Number of Segments

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H5v6l5duGArO-FTRFkZ5rNOEiMcOWI0C
"""

class Solution:
    def countSegments(self, s: str) -> int:
        return len(s.strip().split())