# -*- coding: utf-8 -*-
"""Ransom_note.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H5v6l5duGArO-FTRFkZ5rNOEiMcOWI0C
"""

class Solution:
    def canConstruct(self, ransomNote: str, magazine: str) -> bool:
        r=list(ransomNote)
        m=list(magazine)
        c=0
        for i in r:
            if i in m:
                c=c+1
                m.remove(i)
        if c==len(r):
            return True
        else:
            return False