# -*- coding: utf-8 -*-
"""Repeated_substring

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixGhog27v83jMAJQn1zNkmTGQlFvafaO
"""

class Solution:
    def repeatedSubstringPattern(self, s: str) -> bool:
        if s in (s+s)[1:-1]:
            return True
        else:
            return False

