# -*- coding: utf-8 -*-
"""reverse_words_in_a_string

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ixGhog27v83jMAJQn1zNkmTGQlFvafaO
"""

class Solution:
    def reverseWords(self, s: str) -> str:
        return ' '.join(s.split()[::-1])[::-1]