# -*- coding: utf-8 -*-
"""Reverse Vowel

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18WTAPGxLmzWF316S6D2QvDjeP2UmA3bd
"""

class Solution:
    def reverseVowels(self, s: str) -> str:
        lst=list(s)
        i,j = 0,len(s)-1
        while i<j:
            if lst[i] not in "aeiouAEIOU":
                i+=1
            elif lst[j] not in "aeiouAEIOU":
                j-=1
            else:
                lst[i],lst[j]=lst[j],lst[i]
                i+=1
                j-=1
        return "".join(lst)