# -*- coding: utf-8 -*-
"""To Lower Case

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18WTAPGxLmzWF316S6D2QvDjeP2UmA3bd
"""

class Solution:
    def toLowerCase(self, str: str) -> str:
        return str.lower()