# -*- coding: utf-8 -*-
"""Valid Parentheses.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1o-v6yd-ALmBK9e5tnB-WcuoAMyvDDoMO
"""

class Solution:
    def isValid(self, s: str) -> bool:
        stack = []
        pairs = {'(':')','{':'}','[':']'}
        for char in s:
            if char in pairs:
                stack.append(pairs[char])
            else:
                if len(stack) == 0 or stack.pop() != char:
                    return False
        return len(stack) == 0