# -*- coding: utf-8 -*-
"""Untitled60.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18WTAPGxLmzWF316S6D2QvDjeP2UmA3bd
"""

class Solution:
    def isPalindrome(self, s: str) -> bool:
        s1="".join(i for i in s if i.isalnum()).lower()
        return s1==s1[::-1]