# -*- coding: utf-8 -*-
"""Word_prefix

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12zP-9znMoc27zmEGM2V_vW3qQKPqPqVW
"""

class Solution:
    def isPrefixOfWord(self, sentence: str, searchWord: str) -> int:
        lst=sentence.strip().split()
        c=0
        for word in lst:
            c += 1
            if word[:len(searchWord)]==searchWord:
                return c
                break
        return -1



